services:
  postgres:
    image: postgres:latest
    container_name: postgres_etnair
    env_file:
      - .env
    volumes:
      - etnair_db_data:/var/lib/postgresql/datay
      # - ./.env:/.env
    networks:
      - etnair_network
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_etnair
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - etnair_network

  api:
    image: etnair-api
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: etnair-api
    env_file:
      - .env
      - ./api/.env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - etnair_network

  client:
    image: etnair-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: etnair-client
    env_file:
      - .env
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - etnair_network
  

networks:
  etnair_network:
    driver: bridge

volumes:
  etnair_db_data:
    driver: local
