version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_etnair
    env_file:
      - .env
    volumes:
      - ./api/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - etnair_db_data:/var/lib/postgresql/data
    networks:
      - etnair_network

  api:
    build:
      context: ./api
    container_name: api_etnair
    env_file:
      - .env
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - postgres
    networks:
      - etnair_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_etnair
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - etnair_network

networks:
  etnair_network:
    driver: bridge

volumes:
  etnair_db_data:
    driver: local
